### ISSUE TITLE
Why is the users dir being sent?!

### ISSUE THREAD

**Issue by sam2332** [BLUE-DEVIL1134/BonziBuddy#1]
https://github.com/BLUE-DEVIL1134/BonziBuddy/blob/1bf6185c4c71437413c23f479c2f596152aff91c/BonziBuddy/__init__.py#L471

**Comment by BLUE-DEVIL1134** [comment]
lol, i created this piece of shit when i had just started python...
If you look carefully, it sends the query and the the `Users` dir. My attempt was to send the `query` - `username`.
I had just started python so didnt know much about it and now i dont even care to look back at this project...

* THIS PROJECT IS DEPRECATED !
